### ISSUE TITLE
level="not supported by android"

### ISSUE THREAD

**Issue by rjdesignz** [freshplanet/ANE-In-App-Purchase#3]
I am getting this error while calling the method getProductsInfo. The error is:
[StatusEvent type="status" bubbles=false cancelable=false eventPhase=2 code="PRODUCT_INFO_ERROR" level="not supported by android"]

Also, don't we have to include the Public Key for the inApp billing somewhere in the app?

**Comment by k2xl** [comment]
Same issue! Getting level="not supported by android" right away. Ever fix it?

**Comment by bricecarpentier** [comment]
Seems like GetProductsInfoFunction is not implemented on Android (GetProductsInfoFunction.java is quite explicit about that actually), which is quite logical because this ANE implements IAB v2.

Version 3 of the IAB API does however define the <code>getSkuDetails</code> method which is similar in concept. Anyone fancy implementing it?
