### ISSUE TITLE
I can not get the product info

### ISSUE THREAD

**Issue by laan** [freshplanet/ANE-In-App-Purchase#46]
I thank this is a bug of ANE. Becase I can not get the product info, can not receive the event InAppPurchaseEvent.PRODUCT_INFO_RECEIVED.

**Comment by Jacowaco** [comment]
It works well in Android, but in iOS it the Event is bad and it sends "PRODUCT_INFO_SUCCESS" instead of "PRODUCT_INFO_RECEIVED".

There is already an open Issue about this:
https://github.com/freshplanet/ANE-In-App-Purchase/issues/21

I hope the people at FreshPlanet read this and solves it, as it is a big problem that can be fixed by just changing one line.

**Comment by neuronix** [comment]
Same issue here! :(

**Comment by kerike** [comment]
Hi guys,

I've found a solution. Use tsangwailam's repository.
https://github.com/digicrafts/ANE-In-App-Purchase

He did a merge and a rebuild. I've tested the ane, the adhoc build was successful and the product info shows up. I did a couple of test purchases, and all seems OK. I will update the app in a couple of days, but I think this ane is working fine.

Many thanks to tsangwailam.

**Comment by Jacowaco** [comment]
Yes, that build works well in iOS, but you will have to use the original for Android
