### ISSUE TITLE
Android Package Error

### ISSUE THREAD

**Issue by rainssong** [freshplanet/ANE-In-App-Purchase#62]
\AppData\Local\Temp\94b26edc-2e58-4ce3-b1c2-a197ad5a9f2d\app_entry_
res\values-pl\strings.xml:23: error: Resource at text_runtime_required appears i
n overlay but not in the base package; use <add-resource> to add.

Environment：Air18.0 & Air19.0 + flashdevelop

**Comment by timb1** [comment]
I get the same problem.

**Comment by mental3d** [comment]
Maybe we're doing something wrong.
Hmmm((( I'm upset over that. (rainssong commented on 8 Nov 2015)

**Comment by BearlyEngineering** [comment]
Ive got this problem, AIR 22

**Comment by ghost** [comment]
Had same issue but fixed the problem!
There are some android support classes missing from the package.
I figured this out because the ANE was working fine in one of my projects that includes some ads from Heyzap, but not in other project (without ads), so I just copied the support files into the project and fixed it.
I am using the ANE file (playservices-8.4.0+androidSupport.ane) from this link:
https://s3.amazonaws.com/third-party-sdk/ane_combined_platform_admob_iOS:7.13.0-Android:8.4.0/ane_admob_iOS7.13.0_r1_Android8.4.0_r4.zip
but if you would like, you can just merge the androidSupport jars to the "libAirInAppPurchase.jar" when you recompile it.
Hope this helps :)
